### ISSUE TITLE
Issue with convergence of relativistic electrostatic solver

### ISSUE THREAD

**Issue by EZoni** [ECP-WarpX/WarpX#4093] opened 2023-07-18 20:50 UTC
Originally reported by @aeriforme, later discussed on Slack with @WeiqunZhang and others.

The relativistic electrostatic solver does not converge when running the following input deck: [inputs_3d.txt](https://github.com/ECP-WarpX/WarpX/files/12088776/inputs_3d.txt).

@WeiqunZhang commented this on Slack:

> The solver issue can be fixed with
```
diff --git a/Source/ablastr/utils/Communication.cpp b/Source/ablastr/utils/Communication.cpp
index 71cd83802..a5947f7f3 100644
--- a/Source/ablastr/utils/Communication.cpp
+++ b/Source/ablastr/utils/Communication.cpp
@@ -158,7 +158,8 @@ void SumBoundary (amrex::MultiFab &mf, bool do_single_precision_comms, const amr
     }
     else
     {
-        mf.SumBoundary(period);
+        mf.SumBoundary(0, mf.nComp(), mf.nGrowVect(), period);
+        //mf.SumBoundary(period);
     }
 }
```
>However, this is overkill for non-PEC cases. There are three versions of SumBoundary's in ablastr/utils/Communication.cpp. Their differences are about the number of ghost cells included in the operation. I think we should remove two of them and force us to explicitly think and state the number of source and destination ghost cells.

If the input deck is run on the `development` branch, this is the output of the run:
```
Level 0: dt = 1.042658132e-18 ; dx = 5.46875e-10 ; dy = 5.46875e-10 ; dz = 5.46875e-10

Grids Summary:
  Level 0   64 grids  2097152 cells  100 % of domain
            smallest grid: 32 x 32 x 32  biggest grid: 32 x 32 x 32

-------------------------------------------------------------------------------
--------------------------- MAIN EM PIC PARAMETERS ----------------------------
-------------------------------------------------------------------------------
Precision:            | DOUBLE
Particle precision:   | SINGLE
Geometry:             | 3D (XYZ)
Operation mode:       | Electrostatic
                      | - relativistic
                      | - vacuum
-------------------------------------------------------------------------------
Current Deposition:   | Esirkepov 
Particle Pusher:      | Boris 
Charge Deposition:    | standard 
Field Gathering:      | energy-conserving 
Particle Shape Factor:| 3
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
For full input parameters, see the file: warpx_used_inputs

MLMG: # of AMR levels: 1
      # of MG levels on the coarsest AMR level: 7
MLMG: Initial rhs               = 1.682427141e+24
MLMG: Initial residual (resid0) = 1.682427141e+24
MLMG: Iteration   1 Fine resid/bnorm = 0.3024660864
MLMG: Iteration   2 Fine resid/bnorm = 0.3613926871
MLMG: Iteration   3 Fine resid/bnorm = 0.5134644617
MLMG: Iteration   4 Fine resid/bnorm = 0.7488441616
MLMG: Iteration   5 Fine resid/bnorm = 1.104216645
MLMG: Iteration   6 Fine resid/bnorm = 1.63605428
MLMG: Iteration   7 Fine resid/bnorm = 2.430783981
MLMG: Iteration   8 Fine resid/bnorm = 3.619077171
MLMG: Iteration   9 Fine resid/bnorm = 5.397318621
MLMG: Iteration  10 Fine resid/bnorm = 8.060751514
MLMG: Iteration  11 Fine resid/bnorm = 12.05346564
MLMG: Iteration  12 Fine resid/bnorm = 18.04378285
MLMG: Iteration  13 Fine resid/bnorm = 27.03797105
MLMG: Iteration  14 Fine resid/bnorm = 40.55182273
MLMG: Iteration  15 Fine resid/bnorm = 60.86961578
MLMG: Iteration  16 Fine resid/bnorm = 91.43506203
MLMG: Iteration  17 Fine resid/bnorm = 137.4416624
MLMG: Iteration  18 Fine resid/bnorm = 206.7243865
MLMG: Iteration  19 Fine resid/bnorm = 311.1067727
MLMG: Iteration  20 Fine resid/bnorm = 468.4364757
MLMG: Iteration  21 Fine resid/bnorm = 705.6617069
MLMG: Iteration  22 Fine resid/bnorm = 1063.481705
MLMG: Iteration  23 Fine resid/bnorm = 1603.377834
MLMG: Iteration  24 Fine resid/bnorm = 2418.245789
MLMG: Iteration  25 Fine resid/bnorm = 3648.475931
MLMG: Iteration  26 Fine resid/bnorm = 5506.277296
MLMG: Iteration  27 Fine resid/bnorm = 8312.477047
MLMG: Iteration  28 Fine resid/bnorm = 12552.20205
MLMG: Iteration  29 Fine resid/bnorm = 18959.14316
MLMG: Iteration  30 Fine resid/bnorm = 28643.09208
MLMG: Iteration  31 Fine resid/bnorm = 43282.99882
MLMG: Iteration  32 Fine resid/bnorm = 65419.24847
MLMG: Iteration  33 Fine resid/bnorm = 98896.2068
MLMG: Iteration  34 Fine resid/bnorm = 149532.3764
MLMG: Iteration  35 Fine resid/bnorm = 226135.3535
MLMG: Iteration  36 Fine resid/bnorm = 342039.1728
MLMG: Iteration  37 Fine resid/bnorm = 517433.1847
MLMG: Iteration  38 Fine resid/bnorm = 782890.4094
MLMG: Iteration  39 Fine resid/bnorm = 1184713.765
MLMG: Iteration  40 Fine resid/bnorm = 1793037.683
MLMG: Iteration  41 Fine resid/bnorm = 2714106.567
MLMG: Iteration  42 Fine resid/bnorm = 4108885.524
MLMG: Iteration  43 Fine resid/bnorm = 6221272.102
MLMG: Iteration  44 Fine resid/bnorm = 9420866.585
MLMG: Iteration  45 Fine resid/bnorm = 14267820.52
MLMG: Iteration  46 Fine resid/bnorm = 21611170.55
MLMG: Iteration  47 Fine resid/bnorm = 32737963.26
MLMG: Iteration  48 Fine resid/bnorm = 49599428.27
MLMG: Iteration  49 Fine resid/bnorm = 75154042.2
MLMG: Iteration  50 Fine resid/bnorm = 113887946.2
MLMG: Iteration  51 Fine resid/bnorm = 172604480.2
MLMG: Iteration  52 Fine resid/bnorm = 261622114.3
MLMG: Iteration  53 Fine resid/bnorm = 396592197.9
MLMG: Iteration  54 Fine resid/bnorm = 601257484.7
MLMG: Iteration  55 Fine resid/bnorm = 911638719.3
MLMG: Iteration  56 Fine resid/bnorm = 1382389165
MLMG: Iteration  57 Fine resid/bnorm = 2096440574
MLMG: Iteration  58 Fine resid/bnorm = 3179646768
MLMG: Iteration  59 Fine resid/bnorm = 4823016108
MLMG: Iteration  60 Fine resid/bnorm = 7316468650
MLMG: Iteration  61 Fine resid/bnorm = 1.110009654e+10
MLMG: Iteration  62 Fine resid/bnorm = 1.684200985e+10
MLMG: Iteration  63 Fine resid/bnorm = 2.555656598e+10
MLMG: Iteration  64 Fine resid/bnorm = 3.878394739e+10
MLMG: Iteration  65 Fine resid/bnorm = 5.88629433e+10
MLMG: Iteration  66 Fine resid/bnorm = 8.934534412e+10
MLMG: Iteration  67 Fine resid/bnorm = 1.356255169e+11
MLMG: Iteration  68 Fine resid/bnorm = 2.058969752e+11
MLMG: Iteration  69 Fine resid/bnorm = 3.126058958e+11
MLMG: Iteration  70 Fine resid/bnorm = 4.746599253e+11
MLMG: Iteration  71 Fine resid/bnorm = 7.207850071e+11
MLMG: Iteration  72 Fine resid/bnorm = 1.094627303e+12
MLMG: Iteration  73 Fine resid/bnorm = 1.662508013e+12
MLMG: Iteration  74 Fine resid/bnorm = 2.525211427e+12
MLMG: Iteration  75 Fine resid/bnorm = 3.835905213e+12
MLMG: Iteration  76 Fine resid/bnorm = 5.827384979e+12
MLMG: Iteration  77 Fine resid/bnorm = 8.85349771e+12
MLMG: Iteration  78 Fine resid/bnorm = 1.345212775e+13
MLMG: Iteration  79 Fine resid/bnorm = 2.044097624e+13
MLMG: Iteration  80 Fine resid/bnorm = 3.106321825e+13
MLMG: Iteration  81 Fine resid/bnorm = 4.720902677e+13
MLMG: Iteration  82 Fine resid/bnorm = 7.175250309e+13
MLMG: Iteration  83 Fine resid/bnorm = 1.09064171e+14
MLMG: Iteration  84 Fine resid/bnorm = 1.65790568e+14
MLMG: Iteration  85 Fine resid/bnorm = 2.520402155e+14
MLMG: Iteration  86 Fine resid/bnorm = 3.831879211e+14
MLMG: Iteration  87 Fine resid/bnorm = 5.826199718e+14
MLMG: Iteration  88 Fine resid/bnorm = 8.859111348e+14
MLMG: Iteration  89 Fine resid/bnorm = 1.347180656e+15
MLMG: Iteration  90 Fine resid/bnorm = 2.04876457e+15
MLMG: Iteration  91 Fine resid/bnorm = 3.115935565e+15
MLMG: Iteration  92 Fine resid/bnorm = 4.739305863e+15
MLMG: Iteration  93 Fine resid/bnorm = 7.208925345e+15
MLMG: Iteration  94 Fine resid/bnorm = 1.096618343e+16
MLMG: Iteration  95 Fine resid/bnorm = 1.668281533e+16
MLMG: Iteration  96 Fine resid/bnorm = 2.538117428e+16
MLMG: Iteration  97 Fine resid/bnorm = 3.861733414e+16
MLMG: Iteration  98 Fine resid/bnorm = 5.875986093e+16
MLMG: Iteration  99 Fine resid/bnorm = 8.941426339e+16
MLMG: Iteration 100 Fine resid/bnorm = 1.360692869e+17
MLMG: Iteration 101 Fine resid/bnorm = 2.070810543e+17
MLMG: Iteration 102 Fine resid/bnorm = 3.151717422e+17
MLMG: Iteration 103 Fine resid/bnorm = 4.797119323e+17
MLMG: Iteration 104 Fine resid/bnorm = 7.301966133e+17
MLMG: Iteration 105 Fine resid/bnorm = 1.111539385e+18
MLMG: Iteration 106 Fine resid/bnorm = 1.692136338e+18
MLMG: Iteration 107 Fine resid/bnorm = 2.576149209e+18
MLMG: Iteration 108 Fine resid/bnorm = 3.922216425e+18
MLMG: Iteration 109 Fine resid/bnorm = 5.971957247e+18
MLMG: Iteration 110 Fine resid/bnorm = 9.093396776e+18
MLMG: Iteration 111 Fine resid/bnorm = 1.384712558e+19
MLMG: Iteration 112 Fine resid/bnorm = 2.108710133e+19
MLMG: Iteration 113 Fine resid/bnorm = 3.211423884e+19
MLMG: Iteration 114 Fine resid/bnorm = 4.891044421e+19
MLMG: Iteration 115 Fine resid/bnorm = 7.449524336e+19
amrex::Abort::0::MLMG failing so lets stop here !!!
SIGABRT
MLMG: Iteration 116 Fine resid/bnorm = 1.134692488e+20
MLMG: Failing to converge after 116 iterations. resid, resid/bnorm = 1.909037438e+44, 1.134692488e+20
```

I tried to implement @WeiqunZhang's suggestion in #4078. However, if I try to run the input deck on the branch corresponding to #4078 and with the following modifications, to take into account @WeiqunZhang's fix,
```
diff --git a/Source/Particles/MultiParticleContainer.cpp b/Source/Particles/MultiParticleContainer.cpp
index 10f29aa27..95cdfa3bf 100644
--- a/Source/Particles/MultiParticleContainer.cpp
+++ b/Source/Particles/MultiParticleContainer.cpp
@@ -614,7 +614,7 @@ MultiParticleContainer::GetChargeDensity (int lev, bool local)
     if (!local) {
         const Geometry& gm = allcontainers[0]->Geom(lev);
         ablastr::utils::communication::SumBoundary(
-            *rho, 0, rho->nComp(), rho->nGrowVect(), amrex::IntVect(0),
+            *rho, 0, rho->nComp(), rho->nGrowVect(), rho->nGrowVect(),
             WarpX::do_single_precision_comms, gm.periodicity());
     }
 
diff --git a/Source/Particles/WarpXParticleContainer.cpp b/Source/Particles/WarpXParticleContainer.cpp
index 3d998d88e..bc93bfdc3 100644
--- a/Source/Particles/WarpXParticleContainer.cpp
+++ b/Source/Particles/WarpXParticleContainer.cpp
@@ -1017,7 +1017,7 @@ WarpXParticleContainer::DepositCharge (amrex::Vector<std::unique_ptr<amrex::Mult
         // Exchange guard cells
         if (local == false) {
             ablastr::utils::communication::SumBoundary(
-                *rho[lev], 0, rho[lev]->nComp(), rho[lev]->nGrowVect(), amrex::IntVect(0),
+                *rho[lev], 0, rho[lev]->nComp(), rho[lev]->nGrowVect(), rho[lev]->nGrowVect(),
                 WarpX::do_single_precision_comms, m_gdb->Geom(lev).periodicity());
         }
 
@@ -1112,7 +1112,7 @@ WarpXParticleContainer::GetChargeDensity (int lev, bool local)
 
     if (local == false) {
         ablastr::utils::communication::SumBoundary(
-            *rho, 0, rho->nComp(), rho->nGrowVect(), amrex::IntVect(0),
+            *rho, 0, rho->nComp(), rho->nGrowVect(), rho->nGrowVect(),
             WarpX::do_single_precision_comms, gm.periodicity());
     }
```
the solver still fails to converge. @WeiqunZhang, is this (#4078 + changes posted here) what you had in mind with your suggestion above?

**Comment by WeiqunZhang** [comment] 2023-07-18 22:38
The inputs file here is different from the one I got from @aeriforme. I cannot reproduce the failure even with development branch.

**Comment by WeiqunZhang** [comment] 2023-07-18 22:47
Using this inputs file from @aeriforme [inputuniform.txt](https://github.com/ECP-WarpX/WarpX/files/12089485/inputuniform.txt), I can reproduce the error without the fix. With the fix, it runs. 4 processes were used in my testing.

**Comment by WeiqunZhang** [comment] 2023-07-18 22:50
But if I turn on amrex.fpe_trap_invalid, it crashes later. This was using https://github.com/ECP-WarpX/WarpX/files/12088776/inputs_3d.txt. inputuniform.txt is fine.

**Comment by EZoni** [comment] 2023-07-21 15:34
Update: #4078 now includes the changes described above.

**Comment by EZoni** [comment] 2023-08-08 23:24
@aeriforme Do you think we can close this issue since #4078 has been merged, or were there more issues to be fixed?

**Comment by aeriforme** [comment] 2023-08-09 01:21
Yes, I believe we can close this issue. 
Thank you all!

**Closed as completed by aeriforme** 2023-08-09 01:21 UTC
Labels: bug, component: electrostatic, bug: affects latest release
