### ISSUE TITLE
Boundary reflection problem

### ISSUE THREAD

**Issue by wangjia-ai** [ECP-WarpX/WarpX#2743] opened 2022-01-14 08:08 UTC
Dear developers:
      Is there a way to suppress the internal reflection of laser pulse at the transverse boundary of the box in RZ geometry.
     Thanks!

**Comment by dpgrote** [comment] 2022-01-14 16:55
Which solver are you using, the finite difference or the spectral? With the FD, you can use the Silver-Muller boundary condition, which provides an approximate open boundary condition. With the spectral, the PML boundaries will soon be available.

**Comment by wangjia-ai** [comment] 2022-01-15 01:34
This Silver-Muller boundary condition does not seem to be effective in Yee. The laser pulse is still reflected. The specific input file and the evolution of the laser envelope are as follows.
[inputs_2d.txt](https://github.com/ECP-WarpX/WarpX/files/7874014/inputs_2d.txt)
![laser](https://user-images.githubusercontent.com/73467797/149603899-a5528932-d9cc-458f-a496-4b3dd4888514.gif)

**Comment by RemiLehe** [comment] 2022-01-20 23:54
@wangjia-ai The above results with the Silver-Muller boundary condition is in fact somewhat expected: the issue is that the Silver-Muller is effective at absorbing EM waves in normal incidence, but not so much in grazing incidence (which is the case here with the laser diffracting and impinging on the boundary with a grazing angle).

The PML algorithm is much better at absorbing waves in grazing incidence, but as mentioned by @dpgrote, it is not yet implemented in WarpX, at least in FDTD. But you could switch to the PSATD solver and use the the newly-implemented PML in this case.

**Comment by RemiLehe** [comment] 2022-01-20 23:57
Note also that the progress on the FDTD implementation of the PML is tracked here: https://github.com/ECP-WarpX/WarpX/issues/904

**Comment by RemiLehe** [comment] 2022-01-27 23:42
@wangjia-ai I will close this issue, but feel free to re-open it if needed.

**Closed as completed by RemiLehe** 2022-01-27 23:42 UTC
Labels: question, geometry: RZ, component: boundary
