### ISSUE TITLE
Should we add the `-Werror` compiler flag to the CI builds?

### ISSUE THREAD

**Issue by lucafedeli88** [ECP-WarpX/WarpX#1455] opened 2020-10-22 23:15 UTC
We are very close to eliminate all the compilation warnings for WarpX*, at least when `g++` is used (`clang` is more severe).
As @EZoni and @ax3l have suggested in the past, should we add the `-Werror` compiler flag to the CI builds, so that we can be sure that new PRs do not introduce new warnings?

* to give and idea, if I compile with `cmake` with the default settings and `g++ 9.3.0` I have zero warnings. I get basically just one warning with `g++ 10.2.0`

**Comment by ax3l** [comment] 2020-10-23 01:07
Yay! :tada: I started this in #1457 for the GH action compile checks (NVCC, ICC, DPC++, HIP).

Not sure how to pass this extra flag to the  `regtest.py` suite since it relies on GNUmake that in turn does not incorporate the Unix `CXXFLAGS` environment hints: https://github.com/ECP-WarpX/regression_testing; might need an addition so we can set its `XTRA_CXXFLAGS` without posting it in each entry of the `.ini` file.

**Comment by ax3l** [comment] 2020-10-23 01:11
@WeiqunZhang @atmyers shall we add this to AMReX as well? If we only add this in WarpX CI, we will potentially fail our CI if a new warning is merged into AMReX.

**Comment by ax3l** [comment] 2020-10-23 02:47
We are close! :rocket:

I currently still see those warnings on Summit:
```
./Source/Laser/LaserProfilesImpl/LaserProfileFromTXYEFile.cpp: In member function 'void WarpXLaserProfiles::FromTXYEFileLaserProfile::parse_txye_file(std::__cxx11::string)':
./Source/Laser/LaserProfilesImpl/LaserProfileFromTXYEFile.cpp:134:58: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         m_params.nt = reinterpret_cast<uint32_t*>(buf)[0];
                                                          ^
./Source/Parallelization/WarpXRegrid.cpp: In member function 'void WarpX::LoadBalance()':
./Source/Parallelization/WarpXRegrid.cpp:80:19: warning: conversion to 'std::vector<int, std::allocator<int> >::size_type {aka long unsigned int}' from 'amrex::Real {aka double}' may alter its value [-Wfloat-conversion]
                 pmap.resize(nboxes);
```

The 2nd is #1453

In CI I see in AMReX:
- https://github.com/AMReX-Codes/amrex/issues/1478
- https://github.com/AMReX-Codes/amrex/issues/1479

**Comment by lucafedeli88** [comment] 2020-10-23 16:08
> We are close! rocket
> 
> I currently still see those warnings on Summit:
> 
> ```
> ./Source/Laser/LaserProfilesImpl/LaserProfileFromTXYEFile.cpp: In member function 'void WarpXLaserProfiles::FromTXYEFileLaserProfile::parse_txye_file(std::__cxx11::string)':
> ./Source/Laser/LaserProfilesImpl/LaserProfileFromTXYEFile.cpp:134:58: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>          m_params.nt = reinterpret_cast<uint32_t*>(buf)[0];
>                                                           ^
> ./Source/Parallelization/WarpXRegrid.cpp: In member function 'void WarpX::LoadBalance()':
> ./Source/Parallelization/WarpXRegrid.cpp:80:19: warning: conversion to 'std::vector<int, std::allocator<int> >::size_type {aka long unsigned int}' from 'amrex::Real {aka double}' may alter its value [-Wfloat-conversion]
>                  pmap.resize(nboxes);
> ```
> 
> The 2nd is #1453
> 
> In CI I see in AMReX:
> 
>     * [AMReX-Codes/amrex#1478](https://github.com/AMReX-Codes/amrex/issues/1478)
> 
>     * [AMReX-Codes/amrex#1479](https://github.com/AMReX-Codes/amrex/issues/1479)

Uhm... it's UB right? I think that it is my fault.  I can fix it with something like `std::memcpy(&m_params.nt, buf, sizeof(uint32_t))` .  Actually, I used this unsafe type punning technique multiple times in that file. I will open a PR.

Btw, which combination of compiler and compiler options gave you this warning? I have never seen it on my machines...

**Comment by WeiqunZhang** [comment] 2020-10-23 18:46
With #1466, DPC++ build is warning free for me.

**Comment by lucafedeli88** [comment] 2020-10-24 12:00
> ```
> ./Source/Laser/LaserProfilesImpl/LaserProfileFromTXYEFile.cpp: In member function 'void WarpXLaserProfiles::FromTXYEFileLaserProfile::parse_txye_file(std::__cxx11::string)':
> ./Source/Laser/LaserProfilesImpl/LaserProfileFromTXYEFile.cpp:134:58: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>          m_params.nt = reinterpret_cast<uint32_t*>(buf)[0];

This PR should fix the issue: https://github.com/ECP-WarpX/WarpX/pull/1470 .

**Comment by ax3l** [comment] 2020-10-27 16:22
> Btw, which combination of compiler and compiler options gave you this warning? I have never seen it on my machines...

@lucafedeli88 sorry this slipped me, yes I saw this with GCC 6.4.0 + CUDA on Summit with the usual modules and CMake: https://warpx.readthedocs.io/en/latest/building/summit.html

**Comment by lucafedeli88** [comment] 2020-10-27 17:13
Thanks really a lot @ax3l !

**Comment by ax3l** [comment] 2020-10-27 17:46
> shall we add this to AMReX as well? If we only add this in WarpX CI, we will potentially fail our CI if a new warning is merged into AMReX

As discussed in our developer meeting, let's start with GCC/Clang coverage for host builds: https://github.com/AMReX-Codes/amrex/pull/1484

Then later on add CUDA (besides the already covered `*this` capture that is always an error) and if they become more stable DPC++/SYCL.

**Closed as completed** 2021-07-15 22:56 UTC
Labels: component: tests, warning
