### ISSUE TITLE
macroscopic.epsilon_function(x,y,z) and sigma_function issue: breaks if z dependent

### ISSUE THREAD

**Issue by Poto45** [ECP-WarpX/WarpX#4952] opened 2024-05-26 22:10 UTC
As discussed with Jean-Luc and Axel at IPAC, for epsilon and sigma functions that have a z dependence, the structure "disappears" and is essentially replaced by vacuum. These functions work for simple x-y geometries. I have attached a simplified example that just has the epsilon function, but the same issue arises with the sigma function. The weird thing is that if I am simulating a dielectric structure surrounded by a conductor, if either the epsilon OR the sigma function has z dependence, all structures "disappear". The following are the files attached here with quick descriptions:
- zshift_error_ex.txt - WarpX script detailing a rectangular dielectric tube offset in z by 5 mm. Structure is 100 mm long. Also includes a commented out epsilon function that has only x and y dependence that is known to work. I tried to upload the distribution script that is part of this WarpX script, but it won't take the h5 file. Let me know if there's a way you want me to send that or just use the gaussian bunch created by WarpX as the error will still appear and the difference between distributions should not be too much to recognize that there's an issue here.
- plotscript.txt - Python script to plot the y=0 slice of the transverse force (`np.sqrt(Fx**2+Fy**2)*kV for Fx=-(Exslice-cms*Byslice`) and `Fy=-(Eyslice+cms*Bxslice)`)
- good_diel.png (first image) and bad_diel.png (second image) - good_diel is transverse force plot for a dielectric tube surrounded by a conductor using WarpX functions that do not have z dependence; bad_diel is transverse force plot for dielectric tube without WarpX sigma_function, but PEC boundary in x and y (PML in z), like the zshift_error_ex.3d WarpX script attached.

I'm currently running a simulation without the moving window and while I can't tell exactly quite yet, it does seem like the epsilon function worked for that case. I will update within 24 hours if turning off the moving window works for sure. Thanks!

[zshift_error_ex.txt](https://github.com/ECP-WarpX/WarpX/files/15449134/zshift_error_ex.txt)
[plotscript.txt](https://github.com/ECP-WarpX/WarpX/files/15449135/plotscript.txt)

![good_diel](https://github.com/ECP-WarpX/WarpX/assets/72107916/899c8aea-8532-4de3-b7fb-38d1db257ba8)
![bad_diel](https://github.com/ECP-WarpX/WarpX/assets/72107916/9d86fcf4-4101-4fd8-a1df-4e18e729fc02)

**Comment by ax3l** [comment] 2024-05-29 23:20
Hi @Poto45, thanks for the reproducer! @RemiLehe volunteered to take it on :pray: 

We also added more details on your particle absorber/boundary question, as discussed at IPAC: https://github.com/ECP-WarpX/WarpX/discussions/4755

@Poto45 , if you don't mind, can you complete your profile under https://github.com/settings/profile a bit more (affiliation & full name)? This helps us not to get too confused between people we meet on GitHub and in person :)

**Comment by RemiLehe** [comment] 2024-05-31 13:20
Thanks for reporting this issue.

I am guessing that the problem is indeed with the moving window. My understanding is that, when using the macroscopic properties in WarpX, `epsilon` and `sigma` are computed on the grid at `t=0` (using [this function](https://github.com/ECP-WarpX/WarpX/blob/development/Source/FieldSolver/FiniteDifferenceSolver/MacroscopicProperties/MacroscopicProperties.cpp#L122)) but are never updated as the moving window moves. As a consequence, the simulation will always see the `epsilon` and `sigma` that were initially in the box, even once the moving window has moved far past the its initial positions.

@RevathiJambunathan Is the above correct? Could we in principle add a function that updates `epsilon` and `sigma`, and call it everytime the moving window moves?

**Comment by RevathiJambunathan** [comment] 2024-05-31 14:28
@RemiLehe Yes. you are correct. The (epsilon, sigma, mu) are all initialized at t=0. Updating with moving window will potentially solve this issue.

**Comment by Poto45** [comment] 2024-06-20 15:01
Hello! I wanted to update this page with the case of no moving window. I understand that it was determined that the moving window was the issue, but I wanted to include some figures here for what the results should (probably) look like. Just moving the structure in z was to exemplify the issue, but I'm looking at having a 45 degree cutoff of the structure at the end (with conductor). The warpx script is below with a figure to show what I'm ultimately looking for. 
Is there a timeline for this being updated? Is there anything I can do to help?
Thanks!
[structure_cutoff.txt](https://github.com/user-attachments/files/15915970/structure_cutoff.txt)

![cutoff](https://github.com/ECP-WarpX/WarpX/assets/72107916/a1cb5a57-f504-4755-8a5d-a05423159f94)

**Comment by ax3l** [comment] 2024-06-24 23:47
Hi @Poto45,

Thank you for the update!

Yes, we definitely know what to do ([description](https://github.com/ECP-WarpX/WarpX/issues/4952#issuecomment-2142153242)) now. The issue is that the macroscopic quantities are only initialized at t=0 and not continuously in case of a moving window simulation.

I want to apologize that I initially estimated this is a quick fix. With the steps above, we think it is not hard to fix (~1-2 FTE developer days for fix & testing), but with currently a review we have in house, summer vacation coming up for me, and other commitments @RevathiJambunathan, @RemiLehe and I are too oversubscribed just right now to take it on quickly (i.e., likely not before AAC24).

> Is there anything I can do to help?

Yes, please let this not discourage you to give it a try in the meantime. @RemiLehe linked the respective function and logic above. Currently this logic is only called once during simulation init.

While this stays the same for the [allocations](https://github.com/ECP-WarpX/WarpX/blob/64ab258e93198b87114fb9c92d435809f79608a9/Source/FieldSolver/FiniteDifferenceSolver/MacroscopicProperties/MacroscopicProperties.cpp#L133-L139) (`m_sigma_mf = std::make_unique ...`), the [value assignment](https://github.com/ECP-WarpX/WarpX/blob/64ab258e93198b87114fb9c92d435809f79608a9/Source/FieldSolver/FiniteDifferenceSolver/MacroscopicProperties/MacroscopicProperties.cpp#L140-L201) in those "AMReX MultiFabs" (think: fields) should be called every time step (similar how we continuously inject particles in the moving window for plasma background).

Please feel free to modify it, open a "work-in-progress" (`[WIP]`) pull request so we can help you, and we stay in contact that way and guide you for now?

**Comment by Poto45** [comment] 2024-07-05 14:55
Sounds great! Thanks! I think for right now, the information I need can be calculated from running the simulation without the moving window, so I might wait until you're able to fix that. If I do decide to try the work around, I'll definitely reach out for help. Thanks again!

**Comment by RemiLehe** [comment] 2024-07-24 20:52
@Poto45 Thanks again for reporting this issue.
Would you be able to check whether these changes fix the issue:
https://github.com/ECP-WarpX/WarpX/pull/5082

**Comment by ax3l** [comment] 2024-07-25 17:17
Hi @Poto45, @RemiLehe published a fix in #5082 that we merged into `development`.

We still want to add an automated test with moving window to ensure this functionality is covered and always works. Do you like to help us design a small (<2 CPU cores, few second runtime) test of that kind that we can run and analyze for correctness in the automated tests of WarpX? :) Does not have to be well resolved or converged, just has to check sensibly that the dependency (x,y,z) works.

**Comment by RemiLehe** [comment] 2024-07-29 15:40
@Poto45 confirmed in an email that @5082 fixes the issue.

**Closed as completed by RemiLehe** 2024-07-29 15:40 UTC
Labels: bug, bug: affects latest release, component: core
