### ISSUE TITLE
Ionization Physics: Restart Broken

### ISSUE THREAD

**Issue by wangjia-ai** [ECP-WarpX/WarpX#1546] opened 2020-12-03 10:33 UTC
Dear developers:
        Recently, I was trying a simulation with restart, but I encountered a problem. My steps are as follows:
        
[inputs_2d.txt](https://github.com/ECP-WarpX/WarpX/files/5635437/inputs_2d.txt)

       1: Change  max_step=4  to  max_step=2 ,  and run it.
       2: Change  max_step=2  to  max_step=4 ,and uncomment  amr.restart = diags/chk00002/  , run it.
       but,there is an error: amrex::Abort::0::ParticleContainer::Restart(): ni != NStructInt !!!
       I really don't know how to solve this problem， can you help me??? Really thanks!!!

**Comment by NeilZaim** [comment] 2020-12-08 09:51
Hello @wangjia-ai and thanks a lot for reporting the issue, I am able to reproduce it.

It looks like the checkpoint&restart capability is not yet compatible with field ionization (if I comment the lines concerning ionization in the input file the restart works well), so we'll have to work on that.

**Comment by ax3l** [comment] 2022-06-07 16:40
cc @jjvdwOX I think that is the restart issue you see as well?

**Comment by jameschappell** [comment] 2022-06-08 09:53
Hi @ax3l. Just tested the ionisation restart with the latest version (22.06) and am seeing the same issue. I've attached the input file I used, log and error files and an example Backtrace file. Please let me know if there's anything else you need.

[Input_2D.txt](https://github.com/ECP-WarpX/WarpX/files/8860456/Input_2D.txt)
[errors.txt](https://github.com/ECP-WarpX/WarpX/files/8860457/errors.txt)
[log.txt](https://github.com/ECP-WarpX/WarpX/files/8860459/log.txt)
[warpx_used_inputs.txt](https://github.com/ECP-WarpX/WarpX/files/8860461/warpx_used_inputs.txt)
[Backtrace.457.0.txt](https://github.com/ECP-WarpX/WarpX/files/8860466/Backtrace.457.0.txt)

**Comment by RemiLehe** [comment] 2022-06-22 14:37
I am looking at this currently.

A few remarks:
- I reran the example and it seems that the `ionizationLevel` data is indeed present in the checkpoint file.
- Note that the `log.txt` file contains the following message:
```
--- INFO    : Runtime int component ionizationLevel was found in the checkpoint
             file, but it has not been added yet. Adding it now.
```
which suggests that the function `InitIonizationModule` was not called during the restart.

**Comment by RemiLehe** [comment] 2022-06-22 15:51
Working on fixing this in #3194

**Comment by RemiLehe** [comment] 2022-06-22 17:13
@jameschappell 
Would it be possible for you to compile the code from #3194 and retry the above example?
(No need to re-run the first run - i.e. the one that produced the checkpoints - you can instead directly re-run the restarted run.)

**Comment by jameschappell** [comment] 2022-06-27 08:15
Hi @RemiLehe, sorry for taking so long to get back to you, I was on vacation last week. Can confirm that the code from #3194 works and I am able to restart the above simulation with ionisation. Thanks for fixing this!

**Comment by ax3l** [comment] 2022-07-13 00:17
Fixed via #3194 :tada:

**Closed as completed by ax3l** 2022-07-13 00:17 UTC
Labels: bug, bug: affects latest release, component: core, component: checkpoint/restart

**Comment by BrunoNunes1995** [comment] 2025-06-20 15:10
Dear developers,

I am encountering the same issue reported above, when attempting to restart a simulation from a checkpoint, I get the following error message:

> -- INFO    : Runtime int component ionizationLevel was found in the checkpoint file, but it has not been added yet. Adding it now.
> terminate called after throwing an instance of 'std::runtime_error'
> what():  AddIntComp: name 'ionizationLevel' is already present in the SoA. SIGABRT

I’ve attached two input files: one used to start the simulation ("inputs", renamed to inouts.txt to allow uploade) and another ("inputs_restart") used to restart it from the checkpoint.

Thank you in advance for your assistance.

[inputs.txt](https://github.com/user-attachments/files/20839098/inputs.txt)

[inputs_restart.txt](https://github.com/user-attachments/files/20839104/inputs_restart.txt)

**Comment by titoiride** [comment] 2025-10-16 22:45
I'm seeing the same issue now, a simulation with ionization gives me that SIGABRT at restart.

**Comment by RemiLehe** [comment] 2025-10-22 19:54
@titoiride @BrunoNunes1995 Thanks for reporting this new error.
I am able to reproduce it in a smaller test (See #6291)

**Comment by RemiLehe** [comment] 2025-10-22 20:50
It seems that the bug may have been introduced in this PR:
https://github.com/BLAST-WarpX/warpx/pull/5481/files#diff-2e0df2a796c1fa5c36a6270d3925ad5b46db9653b18278c213382b718b13e4a4
which replaced `NewIntComp` (which can be called several times with the same real time component) with `AddIntComp` (which can only be called once on a real time component, and raises an error if it is called a second time)
