### ISSUE TITLE
Possible back transformed diagnostics issue - missing beam data

### ISSUE THREAD

**Issue by LDAmorim** [ECP-WarpX/WarpX#601] opened 2020-01-08 01:29 UTC
Hi,
@Yin-YinjianZhao pointed out a possible issue to me.
He recently tested the example [inputs.3d.boost](https://github.com/ECP-WarpX/WarpX/blob/dev/Examples/Physics_applications/plasma_acceleration/inputs.3d.boost) and saw no beam data in the snapshots.

With the current code versions, an input (below) that was used for studying the witness beam properties for the previous milestones didn't generate the beam lab frame information as well.

[inputs_3d.txt](https://github.com/ECP-WarpX/WarpX/files/4033217/inputs_3d.txt)

Below is a copy of the output of that run's plotfile beam existing information:
```bash
$ du -h diags/plotfiles/*/beam
4.3M	diags/plotfiles/plt00000/beam/Level_0
4.3M	diags/plotfiles/plt00000/beam
4.3M	diags/plotfiles/plt00500/beam/Level_0
4.3M	diags/plotfiles/plt00500/beam
...
```
And non-existing snapshot information:
```bash
$ du -h lab_frame_data/snapshots/*/beam
  0B	lab_frame_data/snapshots/snapshot00000/beam
  0B	lab_frame_data/snapshots/snapshot00001/beam
...
```
The driver, for example, had information stored:
```bash
$ du -h lab_frame_data/snapshots/*/driver
2.2M	lab_frame_data/snapshots/snapshot00000/driver
2.2M	lab_frame_data/snapshots/snapshot00001/driver
...
```

Also the driverback and beamback back transformed information was not stored.

I don't know if this is because of some not up to date part of the input files or some conflict with recent code changes.
Do any of you have any suggestions on how to understand/fix this?

Thanks

**Comment by LDAmorim** [comment] 2020-01-08 01:31
Both cases were in the 3D geometry, used boosted frame and moving window.

**Comment by Yin-YinjianZhao** [comment] 2020-01-08 19:16
A little bit more information from my side:

With the current code version of WarpX dev, using the example input file Examples/Physics_applications/plasma_acceleration/inputs.3d.boost, the simulation runs until STEP=1270.

```
(base) Bin$ du -sh lab_frame_data/snapshots/*/beam*
  0B	lab_frame_data/snapshots/snapshot00000/beam
  0B	lab_frame_data/snapshots/snapshot00001/beam
  0B	lab_frame_data/snapshots/snapshot00002/beam
  0B	lab_frame_data/snapshots/snapshot00003/beam
  0B	lab_frame_data/snapshots/snapshot00004/beam
  0B	lab_frame_data/snapshots/snapshot00005/beam
  0B	lab_frame_data/snapshots/snapshot00006/beam
  0B	lab_frame_data/snapshots/snapshot00007/beam
  0B	lab_frame_data/snapshots/snapshot00008/beam
  0B	lab_frame_data/snapshots/snapshot00009/beam
  0B	lab_frame_data/snapshots/snapshot00010/beam
  0B	lab_frame_data/snapshots/snapshot00011/beam
  0B	lab_frame_data/snapshots/snapshot00012/beam
  0B	lab_frame_data/snapshots/snapshot00013/beam
  0B	lab_frame_data/snapshots/snapshot00014/beam
  0B	lab_frame_data/snapshots/snapshot00015/beam
  0B	lab_frame_data/snapshots/snapshot00016/beam
  0B	lab_frame_data/snapshots/snapshot00017/beam
  0B	lab_frame_data/snapshots/snapshot00018/beam
  0B	lab_frame_data/snapshots/snapshot00019/beam
  0B	lab_frame_data/snapshots/snapshot00020/beam
  0B	lab_frame_data/snapshots/snapshot00021/beam

```
(base) Bin$ du -sh lab_frame_data/snapshots/*/driver
 56K	lab_frame_data/snapshots/snapshot00000/driver
 56K	lab_frame_data/snapshots/snapshot00001/driver
 56K	lab_frame_data/snapshots/snapshot00002/driver
 56K	lab_frame_data/snapshots/snapshot00003/driver
 56K	lab_frame_data/snapshots/snapshot00004/driver
 56K	lab_frame_data/snapshots/snapshot00005/driver
 56K	lab_frame_data/snapshots/snapshot00006/driver
 56K	lab_frame_data/snapshots/snapshot00007/driver
 56K	lab_frame_data/snapshots/snapshot00008/driver
 56K	lab_frame_data/snapshots/snapshot00009/driver
 56K	lab_frame_data/snapshots/snapshot00010/driver
 56K	lab_frame_data/snapshots/snapshot00011/driver
 56K	lab_frame_data/snapshots/snapshot00012/driver
 56K	lab_frame_data/snapshots/snapshot00013/driver
 56K	lab_frame_data/snapshots/snapshot00014/driver
 56K	lab_frame_data/snapshots/snapshot00015/driver
 56K	lab_frame_data/snapshots/snapshot00016/driver
 56K	lab_frame_data/snapshots/snapshot00017/driver
 56K	lab_frame_data/snapshots/snapshot00018/driver
 56K	lab_frame_data/snapshots/snapshot00019/driver
 56K	lab_frame_data/snapshots/snapshot00020/driver
 56K	lab_frame_data/snapshots/snapshot00021/driver

```
(base) Bin$ du -sh lab_frame_data/snapshots/*/driverback
  0B	lab_frame_data/snapshots/snapshot00000/driverback
  0B	lab_frame_data/snapshots/snapshot00001/driverback
  0B	lab_frame_data/snapshots/snapshot00002/driverback
  0B	lab_frame_data/snapshots/snapshot00003/driverback
  0B	lab_frame_data/snapshots/snapshot00004/driverback
  0B	lab_frame_data/snapshots/snapshot00005/driverback
  0B	lab_frame_data/snapshots/snapshot00006/driverback
  0B	lab_frame_data/snapshots/snapshot00007/driverback
  0B	lab_frame_data/snapshots/snapshot00008/driverback
  0B	lab_frame_data/snapshots/snapshot00009/driverback
  0B	lab_frame_data/snapshots/snapshot00010/driverback
  0B	lab_frame_data/snapshots/snapshot00011/driverback
  0B	lab_frame_data/snapshots/snapshot00012/driverback
  0B	lab_frame_data/snapshots/snapshot00013/driverback
  0B	lab_frame_data/snapshots/snapshot00014/driverback
  0B	lab_frame_data/snapshots/snapshot00015/driverback
  0B	lab_frame_data/snapshots/snapshot00016/driverback
  0B	lab_frame_data/snapshots/snapshot00017/driverback
  0B	lab_frame_data/snapshots/snapshot00018/driverback
  0B	lab_frame_data/snapshots/snapshot00019/driverback
  0B	lab_frame_data/snapshots/snapshot00020/driverback
  0B	lab_frame_data/snapshots/snapshot00021/driverback

```
(base) Bin$ du -sh lab_frame_data/snapshots/*/plasma_e
 28K	lab_frame_data/snapshots/snapshot00000/plasma_e
  0B	lab_frame_data/snapshots/snapshot00001/plasma_e
  0B	lab_frame_data/snapshots/snapshot00002/plasma_e
  0B	lab_frame_data/snapshots/snapshot00003/plasma_e
  0B	lab_frame_data/snapshots/snapshot00004/plasma_e
  0B	lab_frame_data/snapshots/snapshot00005/plasma_e
  0B	lab_frame_data/snapshots/snapshot00006/plasma_e
  0B	lab_frame_data/snapshots/snapshot00007/plasma_e
  0B	lab_frame_data/snapshots/snapshot00008/plasma_e
  0B	lab_frame_data/snapshots/snapshot00009/plasma_e
  0B	lab_frame_data/snapshots/snapshot00010/plasma_e
  0B	lab_frame_data/snapshots/snapshot00011/plasma_e
  0B	lab_frame_data/snapshots/snapshot00012/plasma_e
 28K	lab_frame_data/snapshots/snapshot00013/plasma_e
 28K	lab_frame_data/snapshots/snapshot00014/plasma_e
 28K	lab_frame_data/snapshots/snapshot00015/plasma_e
 28K	lab_frame_data/snapshots/snapshot00016/plasma_e
 28K	lab_frame_data/snapshots/snapshot00017/plasma_e
 28K	lab_frame_data/snapshots/snapshot00018/plasma_e
 28K	lab_frame_data/snapshots/snapshot00019/plasma_e
  0B	lab_frame_data/snapshots/snapshot00020/plasma_e
  0B	lab_frame_data/snapshots/snapshot00021/plasma_e

```
(base) Bin$ du -sh lab_frame_data/snapshots/*/plasma_p
  0B	lab_frame_data/snapshots/snapshot00000/plasma_p
  0B	lab_frame_data/snapshots/snapshot00001/plasma_p
  0B	lab_frame_data/snapshots/snapshot00002/plasma_p
  0B	lab_frame_data/snapshots/snapshot00003/plasma_p
  0B	lab_frame_data/snapshots/snapshot00004/plasma_p
  0B	lab_frame_data/snapshots/snapshot00005/plasma_p
  0B	lab_frame_data/snapshots/snapshot00006/plasma_p
  0B	lab_frame_data/snapshots/snapshot00007/plasma_p
  0B	lab_frame_data/snapshots/snapshot00008/plasma_p
  0B	lab_frame_data/snapshots/snapshot00009/plasma_p
  0B	lab_frame_data/snapshots/snapshot00010/plasma_p
  0B	lab_frame_data/snapshots/snapshot00011/plasma_p
  0B	lab_frame_data/snapshots/snapshot00012/plasma_p
 28K	lab_frame_data/snapshots/snapshot00013/plasma_p
 28K	lab_frame_data/snapshots/snapshot00014/plasma_p
 28K	lab_frame_data/snapshots/snapshot00015/plasma_p
 28K	lab_frame_data/snapshots/snapshot00016/plasma_p
 28K	lab_frame_data/snapshots/snapshot00017/plasma_p
 28K	lab_frame_data/snapshots/snapshot00018/plasma_p
  0B	lab_frame_data/snapshots/snapshot00019/plasma_p
  0B	lab_frame_data/snapshots/snapshot00020/plasma_p
  0B	lab_frame_data/snapshots/snapshot00021/plasma_p

If I run longer until STEP=10000, I will still get the same thing.

**Comment by RevathiJambunathan** [comment] 2020-02-10 21:20
PR#601 that fixes the issue is now merged with dev. Closing issue. Thank you @LDAmorim and @Yin-YinjianZhao for finding it and reporting it.

**Closed by RevathiJambunathan** 2020-02-10 21:20 UTC
