### ISSUE TITLE
CUDA initialization failed

### ISSUE THREAD

**Issue by jinze-liu** [ECP-WarpX/WarpX#5000] opened 2024-06-18 10:57 UTC
When I was running the simulation, I encountered an error with CUDA initialization, as indicated in error file :
[Warpx.error.txt](https://github.com/user-attachments/files/15884914/Warpx.error.txt)
[Backtrace.0.txt](https://github.com/user-attachments/files/15884923/Backtrace.0.txt)

In fact, I had been able to run successfully before, but the error occurred suddenly. I consulted the server administrator, and the response was that there have been no recent updates to the server.

So I am puzzled as to why this error suddenly occurred. Below are my environment script and job submission script: 
[hpc3_gpu_warpx.profile.txt](https://github.com/user-attachments/files/15884929/hpc3_gpu_warpx.profile.txt)
[submit.sh.txt](https://github.com/user-attachments/files/15884932/submit.sh.txt)

**Comment by ax3l** [comment] 2024-06-18 22:23
Thanks for reporting!

Is this on [HPC3 (UCI)](https://warpx.readthedocs.io/en/latest/install/hpc/hpc3.html)?
Can you provide a minimal input file that reproduces this?

From the backtrace, looks like this happens in
```
2. amrex::Gpu::Device::Initialize()+0x1e8b
3. amrex::Initialize(int&, char**&, bool, ompi_communicator_t*, std::function<void ()> const&, std::basic_ostream<char, std::char_traits<char> >&, std::basic_ostream<char, std::char_traits<char> >&, void (*)(char const*))+0x605
4. warpx::initialization::amrex_init(int&, char**&, bool)+0x4e
```

**Comment by WeiqunZhang** [comment] 2024-06-18 22:56
Similar issue: https://github.com/ECP-WarpX/WarpX/issues/4638

**Comment by WeiqunZhang** [comment] 2024-06-18 23:04
Could you run `nvidia-smi` before you run warpx? Mabye there is a mismatch between cuda driver and library.

https://stackoverflow.com/questions/66371130/cuda-initialization-unexpected-error-from-cudagetdevicecount

**Comment by jinze-liu** [comment] 2024-06-23 03:45
Thank you for your help. The issue was resolved by the administrator restarting the cluster. It seems likely that the problem was with the libraries or dependencies on the cluster.

**Comment by ax3l** [comment] 2024-06-24 19:44
Awesome, that great! Thanks for closing the loop here.

**Closed as completed** 2024-06-24 19:44 UTC
Labels: question, machine / system
